# Generated by Django 5.0.3 on 2024-03-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=255)),
                ("format", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(default=0)),
                ("video_file", models.FileField(blank=True, upload_to="videos/")),
                ("audio_file", models.FileField(upload_to="audios/")),
                ("thumbnail", models.ImageField(upload_to="thumnbails/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
