# Generated by Django 5.0.3 on 2024-03-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audios/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
