# Generated by Django 5.0.3 on 2024-06-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloader", "0002_alter_video_audio_file_alter_video_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="pitch_shifted_audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audios/"),
        ),
    ]
